project:
  type: website
  resources:
  - "dynamic"

website:
  title: "Demonax"
  sidebar:
    style: docked
    search: true
    logo: logo.png
    logo-alt: Demonax
    border: false
    contents:
      - section: Home
        contents: qmd/home/*
      - section: Library
        contents: qmd/library/*
      - section: Community
        contents: qmd/community/*

format:
  html:
    fontsize: 1.1em
    theme:
      - cosmo
      - brand
      - styles.scss
    css: styles.css
    toc: true
    mainfont: "Averia Serif Libre"



